name: CapRover Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Installing CapRover CLI
        run: npm install -g caprover
      - name: Set short SHA for tagging Images
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Fetching DOCKER_HUB_TOKEN, CAPROVER_URL, CAPROVER_APP, CAPROVER_APP_URL, CAPROVER_APP_TOKEN and Deploying to CapRover
        env: 
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
          CAPROVER_APP_URL: ${{ secrets.CAPROVER_APP_URL }}
          CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
          SHA: ${{ steps.vars.outputs.sha_short }}
        run: |
          echo "Signing in to Docker..."
          docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"
          echo "Building..."
          export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$DOCKER_HUB_USER/my-build-image:$SHA
          docker build -f ./Dockerfile --pull -t built-image-name .
          docker tag built-image-name "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
          docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
          echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
          echo "Deploying on CapRover..."
          docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_APP_URL --appToken $CAPROVER_APP_TOKEN --caproverApp $CAPROVER_APP --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
      - name: 
      - run: echo "🍏 This job's status is ${{ job.status }}."
