name: CapRover Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing CapRover CLI
        run: npm install -g caprover
      - name: Set short SHA for tagging Images
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Fetching DOCKER_HUB_TOKEN, CAPROVER_URL, CAPROVER_APP, CAPROVER_APP_URL, CAPROVER_APP_TOKEN and Deploying to CapRover
        env: 
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
          CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
          SHA: ${{ steps.vars.outputs.sha_short }}
        run: |
          echo "Signing in to Docker Hub..."
          docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"
          echo "Building..."
          export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$DOCKER_HUB_USER/my-build-image:$SHA
          docker build -f ./Dockerfile --pull -t built-image-name .
          docker tag built-image-name "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
          docker push "$CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
          echo $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
          echo "Deploying on CapRover..."
          docker run caprover/cli-caprover:2.2.3 caprover deploy --appToken $CAPROVER_APP_TOKEN --caproverUrl $CAPROVER_URL --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG --appName $CAPROVER_APP
      - run: echo "🍏 This job's status is ${{ job.status }}."
